title: Your awesome 
author: dereck rock
email: ydrock1@ocdsb.ca
title: hey its ok your welcome
author: DERECK ROCK
email: drock1@ocdsb.ca
description:  
 Hi welcome sub to loltryhard and Aquilax (: also I do coding and make stuff!)

# social links
twitter_username: dont have
github_username:  dereckrocj


show_excerpts: true # set to false to remove excerpts on the homepage
show_excerpts: 

theme: jekyll-theme-merlot 
theme: enaneame
