title: hey its ok your welcome
author: DERECK ROCK
email: drock1@ocdsb.ca
description: > # this means to ignore newlines until "baseurl:"
 Hi welcome sub to loltryhard and Aquilax (: also I do coding and make stuff!

# social links
twitter_username: dont have
github_username:  dereckrocj

show_excerpts: 

theme: minima
